"""add user preferences

Revision ID: cb76a1137a34
Revises: c8f9a1b2d3e4
Create Date: 2026-09-25 22:14:45.163811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb76a1137a34'
down_revision: Union[str, Sequence[str], None] = 'c8f9a1b2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('weekly_analytics_digest_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_analytics_digest_enabled')
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
